-- MySQL Script generated by MySQL Workbench
-- Wed Jul 31 23:13:55 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema premiosdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema premiosdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `premiosdb` DEFAULT CHARACTER SET latin1 ;
USE `premiosdb` ;

-- -----------------------------------------------------
-- Table `premiosdb`.`registros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `premiosdb`.`registros` ;

CREATE TABLE IF NOT EXISTS `premiosdb`.`registros` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `checkbox-persona-moral` BIT(1) NULL DEFAULT NULL,
  `checkbox-persona-fisica` BIT(1) NULL DEFAULT NULL,
  `contacto-nombre` VARCHAR(500) NULL DEFAULT NULL,
  `contacto-telefono` VARCHAR(500) NULL DEFAULT NULL,
  `contacto-email` VARCHAR(500) NULL DEFAULT NULL,
  `checkbox-postumo-si` BIT(1) NULL DEFAULT NULL,
  `checkbox-postumo-no` BIT(1) NULL DEFAULT NULL,
  `checkbox-merito-trayectoria` BIT(1) NULL DEFAULT NULL,
  `checkbox-merito-exatec` BIT(1) NULL DEFAULT NULL,
  `nominado-nombre` VARCHAR(500) NULL DEFAULT NULL,
  `nominado-telefono` VARCHAR(500) NULL DEFAULT NULL,
  `nominado-email` VARCHAR(500) NULL DEFAULT NULL,
  `evidencias` VARCHAR(500) NULL DEFAULT NULL,
  `cv` VARCHAR(500) NULL DEFAULT NULL,
  `ejemplos` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
