-- MySQL Script generated by MySQL Workbench
-- Wed Jul 31 23:13:55 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema premiosdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema premiosdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `premiosdb` DEFAULT CHARACTER SET latin1 ;
USE `premiosdb` ;

-- -----------------------------------------------------
-- Table `premiosdb`.`registros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `premiosdb`.`registros` ;

CREATE TABLE IF NOT EXISTS `premiosdb`.`registros` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `personaMoral` bit(1) DEFAULT NULL,
  `personaFisica` bit(1) DEFAULT NULL,
  `exatecSi` bit(1) DEFAULT NULL,
  `exatecNo` bit(1) DEFAULT NULL,
  `exatecMatricula` varchar(20) DEFAULT NULL,
  `nominacionAnonimaSi` bit(1) DEFAULT NULL,
  `nominacionAnonimaNo` bit(1) DEFAULT NULL,
  `contactoNombre` varchar(500) DEFAULT NULL,
  `contactoTelefono` varchar(500) DEFAULT NULL,
  `contactoEmail` varchar(500) DEFAULT NULL,
  `nominacionPostumaSi` bit(1) DEFAULT NULL,
  `nominacionPostumaNo` bit(1) DEFAULT NULL,
  `trayectoriaExatec` bit(1) DEFAULT NULL,
  `meritoExatec` bit(1) DEFAULT NULL,
  `campus` int(11) DEFAULT NULL,
  `nominadoNombre` varchar(500) DEFAULT NULL,
  `nominadoTelefono` varchar(500) DEFAULT NULL,
  `nominadoEmail` varchar(500) DEFAULT NULL,
  `razonNominacion` longtext DEFAULT NULL,
  `paginaLinkedIn` longtext DEFAULT NULL,
  `evidencia01` varchar(50) DEFAULT NULL,
  `evidencia02` varchar(50) DEFAULT NULL,
  `nominadoCurriculum` varchar(50) DEFAULT NULL,
  `nominadoFoto` varchar(50) DEFAULT NULL,
  `fechaRegistro` date DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
